import { addDays } from '../utils/format';

function repair(data) {
  const receivedAt = addDays(new Date(), -data.daysAgo);
  const promisedAt = addDays(receivedAt, data.promiseIn);
  const deliveredAt = data.status === 'entregada' ? addDays(receivedAt, data.promiseIn) : null;
  const labor = Number(data.labor) || 0;
  const parts = Number(data.parts) || 0;
  return {
    id: data.id,
    number: data.number,
    status: data.status,
    priority: data.priority,
    type: data.type,
    customerName: data.customerName,
    customerPhone: data.customerPhone,
    bike: data.bike,
    color: data.color,
    issue: data.issue,
    technician: data.technician,
    receivedAt,
    promisedAt,
    deliveredAt,
    labor,
    parts,
    total: labor + parts,
    notes: data.notes || null,
    items: data.items || [],
  };
}

export function getDemoRepairs() {
  return [
    repair({
      id: 18,
      number: 86,
      status: 'en_reparacion',
      priority: 'urgente',
      type: 'frenos',
      customerName: 'Valentina Quiroga',
      customerPhone: '11 5488-2301',
      bike: 'Specialized Rockhopper 29"',
      color: 'Negro / verde',
      issue: 'Freno hidráulico trasero sin presión y pastillas gastadas.',
      technician: 'Julián Soto',
      daysAgo: 1,
      promiseIn: 2,
      labor: 18000,
      parts: 24600,
      items: [
        { description: 'Sangrado de freno hidráulico', quantity: 1, unitPrice: 18000, kind: 'mano_obra' },
        { description: 'Pastillas orgánicas Shimano', quantity: 1, unitPrice: 14600, kind: 'repuesto' },
        { description: 'Líquido mineral', quantity: 1, unitPrice: 10000, kind: 'repuesto' },
      ],
    }),
    repair({
      id: 17,
      number: 85,
      status: 'recepcionada',
      priority: 'alta',
      type: 'electrico',
      customerName: 'Hernán Paz',
      customerPhone: '11 4122-9088',
      bike: 'Venzo E-Volt 500W',
      color: 'Gris',
      issue: 'No enciende la batería. Revisar conector y display.',
      technician: 'Marina López',
      daysAgo: 0,
      promiseIn: 4,
      labor: 22000,
      parts: 0,
      notes: 'Cliente deja cargador original.',
      items: [
        { description: 'Diagnóstico sistema eléctrico', quantity: 1, unitPrice: 22000, kind: 'mano_obra' },
      ],
    }),
    repair({
      id: 16,
      number: 84,
      status: 'lista',
      priority: 'media',
      type: 'service',
      customerName: 'Carla Méndez',
      customerPhone: '11 3901-4472',
      bike: 'Trek Marlin 7',
      color: 'Azul',
      issue: 'Service de temporada y regulación de cambios.',
      technician: 'Pablo Rivas',
      daysAgo: 3,
      promiseIn: 3,
      labor: 28000,
      parts: 8500,
      items: [
        { description: 'Service completo', quantity: 1, unitPrice: 28000, kind: 'mano_obra' },
        { description: 'Cable de cambio', quantity: 1, unitPrice: 8500, kind: 'repuesto' },
      ],
    }),
    repair({
      id: 15,
      number: 83,
      status: 'en_reparacion',
      priority: 'media',
      type: 'transmision',
      customerName: 'Ignacio Varela',
      customerPhone: '11 6230-1184',
      bike: 'Olmo Wish 28"',
      color: 'Blanco',
      issue: 'Cadena salta en plato grande. Posible desgaste de cassette.',
      technician: 'Julián Soto',
      daysAgo: 2,
      promiseIn: 3,
      labor: 16000,
      parts: 42000,
      items: [
        { description: 'Cambio de cassette 9v', quantity: 1, unitPrice: 38000, kind: 'repuesto' },
        { description: 'Cadena KMC', quantity: 1, unitPrice: 4000, kind: 'repuesto' },
        { description: 'Montaje y regulación', quantity: 1, unitPrice: 16000, kind: 'mano_obra' },
      ],
    }),
    repair({
      id: 14,
      number: 82,
      status: 'recepcionada',
      priority: 'baja',
      type: 'ruedas',
      customerName: 'Sofía Gallo',
      customerPhone: '11 4788-0091',
      bike: 'Top Mega Sunshine 26"',
      color: 'Rosa',
      issue: 'Cubierta pinchada y rayos flojos en rueda delantera.',
      technician: 'Marina López',
      daysAgo: 0,
      promiseIn: 1,
      labor: 9000,
      parts: 18500,
      items: [
        { description: 'Centado de rueda', quantity: 1, unitPrice: 9000, kind: 'mano_obra' },
        { description: 'Cubierta 26x2.10', quantity: 1, unitPrice: 18500, kind: 'repuesto' },
      ],
    }),
    repair({
      id: 13,
      number: 81,
      status: 'entregada',
      priority: 'media',
      type: 'service',
      customerName: 'Martín Álvarez',
      customerPhone: '11 5550-2210',
      bike: 'Giant Talon 29"',
      color: 'Rojo',
      issue: 'Puesta a punto post-compra y ajuste de asiento.',
      technician: 'Pablo Rivas',
      daysAgo: 8,
      promiseIn: 2,
      labor: 15000,
      parts: 0,
      items: [
        { description: 'Puesta a punto', quantity: 1, unitPrice: 15000, kind: 'mano_obra' },
      ],
    }),
    repair({
      id: 12,
      number: 80,
      status: 'lista',
      priority: 'alta',
      type: 'garantia',
      customerName: 'Club Ciclista Norte',
      customerPhone: '11 4002-8811',
      bike: 'Scott Scale 970',
      color: 'Negro',
      issue: 'Horquilla con pérdida de aire. Cubierta por garantía.',
      technician: 'Julián Soto',
      daysAgo: 5,
      promiseIn: 7,
      labor: 0,
      parts: 0,
      notes: 'Sin cargo — garantía de fábrica.',
      items: [
        { description: 'Revisión de horquilla en garantía', quantity: 1, unitPrice: 0, kind: 'mano_obra' },
      ],
    }),
    repair({
      id: 11,
      number: 79,
      status: 'entregada',
      priority: 'media',
      type: 'frenos',
      customerName: 'Lucía Fernández',
      customerPhone: '11 4330-7765',
      bike: 'Cannondale Trail 5',
      color: 'Celeste',
      issue: 'Ajuste de frenos a disco y cintas de manubrio.',
      technician: 'Marina López',
      daysAgo: 12,
      promiseIn: 1,
      labor: 12000,
      parts: 6500,
      items: [
        { description: 'Regulación de frenos', quantity: 1, unitPrice: 12000, kind: 'mano_obra' },
        { description: 'Cinta de manubrio', quantity: 1, unitPrice: 6500, kind: 'repuesto' },
      ],
    }),
    repair({
      id: 10,
      number: 78,
      status: 'cancelada',
      priority: 'baja',
      type: 'diagnostico',
      customerName: 'Diego Roldán',
      customerPhone: '11 4900-1288',
      bike: 'Bicicleta urbana rodado 28',
      color: 'Verde',
      issue: 'Ruidos en caja pedalera. Cliente retiró sin reparar.',
      technician: 'Pablo Rivas',
      daysAgo: 16,
      promiseIn: 3,
      labor: 8000,
      parts: 0,
      notes: 'Cancelada a pedido del cliente.',
      items: [
        { description: 'Diagnóstico', quantity: 1, unitPrice: 8000, kind: 'mano_obra' },
      ],
    }),
  ].sort((a, b) => b.number - a.number);
}
