import { addDays, computeInvoiceTotals } from '../utils/format';

function invoice({ id, number, type, status, customerName, customerDoc, customerCondition, daysAgo, dueIn, paymentMethod, notes, items, cae }) {
  const date = addDays(new Date(), -daysAgo);
  const dueDate = addDays(date, dueIn);
  const totals = computeInvoiceTotals(items, type);
  return {
    id,
    number,
    pos: 1,
    type,
    status,
    customerName,
    customerDoc,
    customerCondition,
    date,
    dueDate,
    paymentMethod,
    notes: notes || null,
    cae,
    caeDue: addDays(date, 10),
    items: items.map((item, index) => ({
      id: id * 10 + index,
      description: item.description,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      taxPct: type === 'C' ? 0 : 21,
      subtotal: item.quantity * item.unitPrice,
    })),
    ...totals,
  };
}

export function getDemoInvoices() {
  return [
    invoice({
      id: 12,
      number: 128,
      type: 'B',
      status: 'pagada',
      customerName: 'Martín Álvarez',
      customerDoc: '32456789',
      customerCondition: 'Consumidor Final',
      daysAgo: 1,
      dueIn: 0,
      paymentMethod: 'tarjeta',
      cae: '74192836501247',
      items: [
        { description: 'Bicicleta MTB 29" aluminio', quantity: 1, unitPrice: 890000 },
        { description: 'Casco MTB ventilado', quantity: 1, unitPrice: 78000 },
      ],
    }),
    invoice({
      id: 11,
      number: 127,
      type: 'A',
      status: 'emitida',
      customerName: 'Rutas del Sur S.R.L.',
      customerDoc: '30715482913',
      customerCondition: 'IVA Responsable Inscripto',
      daysAgo: 3,
      dueIn: 15,
      paymentMethod: 'transferencia',
      notes: 'Orden de compra OC-441',
      cae: '74192836501238',
      items: [
        { description: 'Servicio de armado y puesta a punto', quantity: 4, unitPrice: 45000 },
        { description: 'Kit de luces USB delantera/trasera', quantity: 4, unitPrice: 32000 },
      ],
    }),
    invoice({
      id: 10,
      number: 126,
      type: 'B',
      status: 'pagada',
      customerName: 'Lucía Fernández',
      customerDoc: '38551220',
      customerCondition: 'Consumidor Final',
      daysAgo: 5,
      dueIn: 0,
      paymentMethod: 'contado',
      cae: '74192836501221',
      items: [
        { description: 'Indumentaria jersey verano', quantity: 2, unitPrice: 42000 },
        { description: 'Guantes cortos gel', quantity: 1, unitPrice: 18500 },
      ],
    }),
    invoice({
      id: 9,
      number: 125,
      type: 'B',
      status: 'vencida',
      customerName: 'Diego Roldán',
      customerDoc: '27890112',
      customerCondition: 'Consumidor Final',
      daysAgo: 22,
      dueIn: 7,
      paymentMethod: 'plazo',
      notes: 'Seña 30% — saldo pendiente',
      cae: '74192836499810',
      items: [
        { description: 'Bicicleta urbana rodado 28', quantity: 1, unitPrice: 620000 },
      ],
    }),
    invoice({
      id: 8,
      number: 124,
      type: 'B',
      status: 'pagada',
      customerName: 'Camila Soto',
      customerDoc: '40122334',
      customerCondition: 'Consumidor Final',
      daysAgo: 18,
      dueIn: 0,
      paymentMethod: 'transferencia',
      cae: '74192836499002',
      items: [
        { description: 'Neumático 29x2.20 kevlar', quantity: 2, unitPrice: 54000 },
        { description: 'Cámara 29" válvula prestá', quantity: 2, unitPrice: 8500 },
      ],
    }),
    invoice({
      id: 7,
      number: 123,
      type: 'A',
      status: 'pagada',
      customerName: 'Club Ciclista Norte',
      customerDoc: '33711220954',
      customerCondition: 'IVA Responsable Inscripto',
      daysAgo: 28,
      dueIn: 10,
      paymentMethod: 'transferencia',
      cae: '74192836498117',
      items: [
        { description: 'Casco ruta aerodinámico', quantity: 8, unitPrice: 96000 },
        { description: 'Bidón 750 ml', quantity: 12, unitPrice: 6200 },
      ],
    }),
    invoice({
      id: 6,
      number: 122,
      type: 'C',
      status: 'pagada',
      customerName: 'Taller Pedal Libre',
      customerDoc: '20345678901',
      customerCondition: 'IVA Monotributo',
      daysAgo: 36,
      dueIn: 0,
      paymentMethod: 'contado',
      cae: '74192836497044',
      items: [
        { description: 'Repuestos transmisión 11v', quantity: 1, unitPrice: 128000 },
      ],
    }),
    invoice({
      id: 5,
      number: 121,
      type: 'B',
      status: 'anulada',
      customerName: 'Pablo Medina',
      customerDoc: '29988776',
      customerCondition: 'Consumidor Final',
      daysAgo: 40,
      dueIn: 0,
      paymentMethod: 'tarjeta',
      notes: 'Anulada por devolución de mercadería',
      cae: '74192836496100',
      items: [
        { description: 'Asiento ergonómico gel', quantity: 1, unitPrice: 36500 },
      ],
    }),
    invoice({
      id: 4,
      number: 120,
      type: 'B',
      status: 'pagada',
      customerName: 'Ana Ruiz',
      customerDoc: '35100221',
      customerCondition: 'Consumidor Final',
      daysAgo: 55,
      dueIn: 0,
      paymentMethod: 'tarjeta',
      cae: '74192836495018',
      items: [
        { description: 'Bicicleta infantil rodado 20', quantity: 1, unitPrice: 245000 },
        { description: 'Candado U-lock', quantity: 1, unitPrice: 28000 },
      ],
    }),
    invoice({
      id: 3,
      number: 119,
      type: 'B',
      status: 'emitida',
      customerName: 'Nicolás Herrera',
      customerDoc: '42115678',
      customerCondition: 'Consumidor Final',
      daysAgo: 2,
      dueIn: 7,
      paymentMethod: 'plazo',
      notes: 'Service en mostrador',
      cae: '74192836501302',
      items: [
        { description: 'Servicio de service completo', quantity: 1, unitPrice: 38000 },
        { description: 'Pastillas de freno orgánicas', quantity: 1, unitPrice: 14500 },
      ],
    }),
    invoice({
      id: 2,
      number: 104,
      type: 'B',
      status: 'pagada',
      customerName: 'Laura Paredes',
      customerDoc: '30111222',
      customerCondition: 'Consumidor Final',
      daysAgo: 95,
      dueIn: 0,
      paymentMethod: 'tarjeta',
      cae: '74192836488011',
      items: [
        { description: 'Bicicleta paseo rodado 26', quantity: 1, unitPrice: 410000 },
      ],
    }),
    invoice({
      id: 1,
      number: 91,
      type: 'A',
      status: 'pagada',
      customerName: 'Escuela de Ciclismo Sur',
      customerDoc: '30788900123',
      customerCondition: 'IVA Responsable Inscripto',
      daysAgo: 130,
      dueIn: 15,
      paymentMethod: 'transferencia',
      cae: '74192836480120',
      items: [
        { description: 'Cascos infantiles pack x10', quantity: 1, unitPrice: 320000 },
        { description: 'Kit de luces USB', quantity: 10, unitPrice: 18000 },
      ],
    }),
  ].sort((a, b) => b.number - a.number);
}

export function nextDemoCae() {
  const n = 74192836500000 + Math.floor(Math.random() * 90000);
  return String(n);
}
